[theme]
primaryColor = "#0B6E99"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F8FA"
textColor = "#1B1F23"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
